services:
  - type: web
    name: pagina-42-livros-api
    runtime: node
    plan: free
    region: oregon
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: API_KEY
        sync: false
